modLoader="kotlinforforge"
loaderVersion="[2.0,)"
license="LGPL v2.1"

[[mods]]
displayName="Kotlin for Forge"
modId="kotlinforforge"
version="2.0.0"
authors="TheDarkColour"
credits="Herobrine knows all. Thanks to Username404-59 and TheOnlyTails on GitHub"
issueTrackerURL="https://github.com/thedarkcolour/KotlinForForge/issues"
description='''
Kotlin for Forge. Allows mods to use the Kotlin programming language.
'''

[[dependencies.kotlinforforge]]
modId="forge"
mandatory=true
versionRange="[37,)"
ordering="NONE"
side="BOTH"
[[dependencies.kotlinforforge]]
modId="minecraft"
mandatory=true
versionRange="[1.17,1.18)"
ordering="NONE"
side="BOTH"