{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflib-neoforge",
    "version": "5.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kfflib-neoforge-5.4.0.jar",
          "url": "kfflib-neoforge-5.4.0.jar",
          "size": 38834,
          "sha512": "7b87e31c3c107e66ecb0d10d83d95683f5d0662cba3538abb934cf2daa04fc2590757a191e3bf90c84bda27d294302d4127912c7634562e4640c4dc2ce9773ce",
          "sha256": "3ba77995efe861f5c849b1cec3bc11041f636c19643a0b02bf810c7770d77994",
          "sha1": "62e8ad8430ab73402e8da98aef35d497eead660a",
          "md5": "78b5d94057284eeb1d95dabc8b98f8d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kfflib-neoforge-5.4.0.jar",
          "url": "kfflib-neoforge-5.4.0.jar",
          "size": 38834,
          "sha512": "7b87e31c3c107e66ecb0d10d83d95683f5d0662cba3538abb934cf2daa04fc2590757a191e3bf90c84bda27d294302d4127912c7634562e4640c4dc2ce9773ce",
          "sha256": "3ba77995efe861f5c849b1cec3bc11041f636c19643a0b02bf810c7770d77994",
          "sha1": "62e8ad8430ab73402e8da98aef35d497eead660a",
          "md5": "78b5d94057284eeb1d95dabc8b98f8d6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflib-neoforge-5.4.0-sources.jar",
          "url": "kfflib-neoforge-5.4.0-sources.jar",
          "size": 11909,
          "sha512": "c872c92a6c442c8238bf0f572fbccd70f385f0841456ffcfa970e17fa077ae792705219cb7480f841b6230aec34525c7abccae09c11f9e2d06921d96f62b1acb",
          "sha256": "9f90760957bfd912a19586b0a8612048395275e2461169d2afcd0bd2a787de10",
          "sha1": "7fecec81837b0ef0bfd4e2c5fb239ea82d499a7b",
          "md5": "5b1d6bc65f39ba4cad61ee8358a5c68b"
        }
      ]
    }
  ]
}
