{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflib-neoforge",
    "version": "5.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kfflib-neoforge-5.4.0.jar",
          "url": "kfflib-neoforge-5.4.0.jar",
          "size": 38834,
          "sha512": "8bb82c79bbc7b1ae05da69d4283ea417d33c6aebb7594765528d0fd735f973f85409da0ee7f38ca52ad265e2400ba7afce163cce064aa90885b445ee35bb576d",
          "sha256": "2feb4065cfef53714255679f39cf2290d15b50dd6be89dafeb0d6c2752feb82b",
          "sha1": "ebc0939630bd28205c865c037a7b3c1df924e76a",
          "md5": "4cb73803bba36c43a4fab4e578d62d26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kfflib-neoforge-5.4.0.jar",
          "url": "kfflib-neoforge-5.4.0.jar",
          "size": 38834,
          "sha512": "8bb82c79bbc7b1ae05da69d4283ea417d33c6aebb7594765528d0fd735f973f85409da0ee7f38ca52ad265e2400ba7afce163cce064aa90885b445ee35bb576d",
          "sha256": "2feb4065cfef53714255679f39cf2290d15b50dd6be89dafeb0d6c2752feb82b",
          "sha1": "ebc0939630bd28205c865c037a7b3c1df924e76a",
          "md5": "4cb73803bba36c43a4fab4e578d62d26"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflib-neoforge-5.4.0-sources.jar",
          "url": "kfflib-neoforge-5.4.0-sources.jar",
          "size": 11909,
          "sha512": "6a20133161ce267d644f5a438b403ed4e2970484e7f8b46d75ff0328a3abe8534ca11b99028eca8ce5e938b02b8fdc105fcd7c169ff00c272db5aee0bc53db72",
          "sha256": "1b42272d9057873b2458f699de979c712378b78d4c749643cb701562015a3720",
          "sha1": "604c25e7ce5622edd0231d2ab2b4b5a4e900d092",
          "md5": "23485f28b96bbb7379f07232f018cdc8"
        }
      ]
    }
  ]
}
