{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kffmod-neoforge",
    "version": "5.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kffmod-neoforge-5.4.0.jar",
          "url": "kffmod-neoforge-5.4.0.jar",
          "size": 69633,
          "sha512": "87927a4f7d9246b1cf9ba32a7394a6efee40172c02ac1990724d990d5953bc8e48ecac2528693a2299be1e00b7d808239cd5e4075dd96ebbd43628fc4171bfcc",
          "sha256": "c1b92a42031a1243c8357b6679e3cdf333338f63492b39cd17ef0b02938e46ab",
          "sha1": "19db174a9af20af37d0f77ee914c6c4f8c75a5f1",
          "md5": "5e0c8d77236c4d16794b4aeb26486150"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.neoforged.fancymodloader",
          "module": "loader",
          "version": {
            "requires": "[3,5)"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kfflib-neoforge",
          "version": {
            "requires": "5.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kffmod-neoforge-5.4.0.jar",
          "url": "kffmod-neoforge-5.4.0.jar",
          "size": 69633,
          "sha512": "87927a4f7d9246b1cf9ba32a7394a6efee40172c02ac1990724d990d5953bc8e48ecac2528693a2299be1e00b7d808239cd5e4075dd96ebbd43628fc4171bfcc",
          "sha256": "c1b92a42031a1243c8357b6679e3cdf333338f63492b39cd17ef0b02938e46ab",
          "sha1": "19db174a9af20af37d0f77ee914c6c4f8c75a5f1",
          "md5": "5e0c8d77236c4d16794b4aeb26486150"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kffmod-neoforge-5.4.0-sources.jar",
          "url": "kffmod-neoforge-5.4.0-sources.jar",
          "size": 68961,
          "sha512": "d5963479ebc93c15401a5057e4bf7b05170e896fd3ad9749246d2ffe86fa1595b3f72c8b31aeefb146b3637d4eddfc86d328d02f46977b8785ac326baf80c39b",
          "sha256": "bf607e266b3e29aefef4ced1e8768655a619897554696dc9a30dcfba0cc6728f",
          "sha1": "3efa0bf76ef24f90f6bd8e0e8448681a23d1c574",
          "md5": "bf6b1bbdb5e79ebbcf4f1d7faf402fdf"
        }
      ]
    }
  ]
}
