{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflang",
    "version": "5.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kfflang-5.4.0.jar",
          "url": "kfflang-5.4.0.jar",
          "size": 23497,
          "sha512": "60529e981496d1c704f1d6455717abd7518e2aa9b161a7f5e3cdef44561fce5dd30f481fb3ae44f32fbbaf3ad802e0642058e899b8c535b9bc5928f4101df80a",
          "sha256": "1b41a13650930e245069e3db526c74ea97e5e85a2b840a8c6493ddd2e31d8970",
          "sha1": "cbbf85c4cbb09a3aef4766d6011218f9f1447bbe",
          "md5": "8523a04aa7f45c72f0d30269622408a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kfflang-5.4.0.jar",
          "url": "kfflang-5.4.0.jar",
          "size": 23497,
          "sha512": "60529e981496d1c704f1d6455717abd7518e2aa9b161a7f5e3cdef44561fce5dd30f481fb3ae44f32fbbaf3ad802e0642058e899b8c535b9bc5928f4101df80a",
          "sha256": "1b41a13650930e245069e3db526c74ea97e5e85a2b840a8c6493ddd2e31d8970",
          "sha1": "cbbf85c4cbb09a3aef4766d6011218f9f1447bbe",
          "md5": "8523a04aa7f45c72f0d30269622408a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflang-5.4.0-sources.jar",
          "url": "kfflang-5.4.0-sources.jar",
          "size": 7440,
          "sha512": "1c63ae58e1e3574e4e65b21dd67ce211ebe8c3edbf39dda159964c79cd528e98cc8f22663e034eb0f00721686dfdfa73bbf2725c9918194edcab00dafb15e995",
          "sha256": "02ee767f1f56854ec61c1b82c9f2a375a049ead031aea0b6391e43dd3eb669c7",
          "sha1": "13b755aca4bde085a767bfd3a8abca914160c11e",
          "md5": "67dba4ca8ef3b9d7654fd4286b17b421"
        }
      ]
    }
  ]
}
