{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflib",
    "version": "5.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kfflib-5.4.0.jar",
          "url": "kfflib-5.4.0.jar",
          "size": 41497,
          "sha512": "2eefdefa6ac4aa0f059f4bd58d72e2c18de81085744049e46a05798494540ad78d4569bd0a0dd85df652a1123fe19c51b41196e16ad7a6c15a8bfa59dee034b8",
          "sha256": "2bd26fc311b427b3919cd222dc94d8df74acc48823b116212fcaa94c8af47e94",
          "sha1": "083fc35c18f4ac837716c94d27c2e83479a701ba",
          "md5": "ab738bfed75670673b1b6c871c558767"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kfflib-5.4.0.jar",
          "url": "kfflib-5.4.0.jar",
          "size": 41497,
          "sha512": "2eefdefa6ac4aa0f059f4bd58d72e2c18de81085744049e46a05798494540ad78d4569bd0a0dd85df652a1123fe19c51b41196e16ad7a6c15a8bfa59dee034b8",
          "sha256": "2bd26fc311b427b3919cd222dc94d8df74acc48823b116212fcaa94c8af47e94",
          "sha1": "083fc35c18f4ac837716c94d27c2e83479a701ba",
          "md5": "ab738bfed75670673b1b6c871c558767"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflib-5.4.0-sources.jar",
          "url": "kfflib-5.4.0-sources.jar",
          "size": 12417,
          "sha512": "7fbb3efa750f82ceba50ef5163e8c1c0f593101142d0770622ef8f52c366a94e0421af8c597bd31348952f73febfa8b324ff060ca7d60b6c044fb88b20884ff5",
          "sha256": "4a4e0c855fd9852e56bea902cbbdd13c951c75e6c3ccf2112dd035c95c7e2fa1",
          "sha1": "42e84b66b075fa3e6688f09c826f4c6a9f4a2514",
          "md5": "82a3607db1d9f1c720d72028cc884b31"
        }
      ]
    }
  ]
}
