{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kotlinforforge",
    "version": "5.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kfflang",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kfflib",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kffmod",
          "version": {
            "requires": "5.4.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kfflang",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kfflib",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kffmod",
          "version": {
            "requires": "5.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinforforge-5.4.0-all.jar",
          "url": "kotlinforforge-5.4.0-all.jar",
          "size": 6306611,
          "sha512": "418344c0da0026425c09f1ea2d2194b534d6199d05492aaf579f641269af3c07a2d81adf98fb4225ce6ca675366e33d0821ffcf11cdd83093668ec3e2f60556a",
          "sha256": "78eb6614ad8237849acd171b45ff0dd60db7d7826aabe62a9aa75d6b6f1253d8",
          "sha1": "d8e181e852a6fd8ff74cce924ea05e15099f853c",
          "md5": "753f6fd3b19322f3a6e379cf05eab6f7"
        }
      ]
    }
  ]
}
