{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflang-neoforge",
    "version": "5.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kfflang-neoforge-5.3.0.jar",
          "url": "kfflang-neoforge-5.3.0.jar",
          "size": 20421,
          "sha512": "d0dfd8acda2462aa497ddf44fd9218c5d79793bb8135d85b2ef7f5e027f0e2b1a6201ab6133fddeaf9ddbb1394b5f017e7041e6cbd28421a8cb908539d68e112",
          "sha256": "176015a5766e2e64e8d4eaf28b3a571851dee0e93756f1f906ba68aa872643b8",
          "sha1": "fceceb1f8fa726131fe87b8cdc14a65d15c88d61",
          "md5": "7f622f8bacf5b0a95df140246d074dc6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.neoforged.fancymodloader",
          "module": "loader",
          "version": {
            "requires": "[3,5)"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kfflang-neoforge-5.3.0.jar",
          "url": "kfflang-neoforge-5.3.0.jar",
          "size": 20421,
          "sha512": "d0dfd8acda2462aa497ddf44fd9218c5d79793bb8135d85b2ef7f5e027f0e2b1a6201ab6133fddeaf9ddbb1394b5f017e7041e6cbd28421a8cb908539d68e112",
          "sha256": "176015a5766e2e64e8d4eaf28b3a571851dee0e93756f1f906ba68aa872643b8",
          "sha1": "fceceb1f8fa726131fe87b8cdc14a65d15c88d61",
          "md5": "7f622f8bacf5b0a95df140246d074dc6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflang-neoforge-5.3.0-sources.jar",
          "url": "kfflang-neoforge-5.3.0-sources.jar",
          "size": 6914,
          "sha512": "957f810c6f385147ecab9c041e204143e6b4b9cd140a76c40b2945c4f2eac17de2422b6a4d844ed4980e8e1e2ea1980712856715b9dd107f694a64075596ebee",
          "sha256": "957884956ec547b9e2259664bab7742ca8ff1291baf5de42db81f1e32e71783f",
          "sha1": "2dc3e94bcdf39dc04195cb83b8fda1ca46fe564c",
          "md5": "1200b9511aee31ef325f127a5bedb6c2"
        }
      ]
    }
  ]
}
