{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kotlinforforge-neoforge",
    "version": "5.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kfflang-neoforge",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kfflib-neoforge",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kffmod-neoforge",
          "version": {
            "requires": "5.3.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kfflang-neoforge",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kfflib-neoforge",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kffmod-neoforge",
          "version": {
            "requires": "5.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinforforge-neoforge-5.3.0-all.jar",
          "url": "kotlinforforge-neoforge-5.3.0-all.jar",
          "size": 6303349,
          "sha512": "4a799c43e10dcea61f36aff478873697780610fd2314d671e72eec536b85098acea876528dbb232171325ad63ea17115ee4fed02680a7e18e3b27187a70f7afb",
          "sha256": "7ff0d6c96bf84a8141f42e20c6c46767fb749f448b3c8224fbbcbb01adb2a84a",
          "sha1": "8ee9802e5517f3fc7837dba95a1209545d105038",
          "md5": "d1ac5c2425f62412a05b0a1d2240a254"
        }
      ]
    }
  ]
}
